version: '3.8'

services:
  web:
    environment:
      APP_TARGET: web
    container_name: "time-tracker-web"
    build:
      context: web-app
      dockerfile: Dockerfile
    ports:
      - "9020:80"
    restart: always
